---
- name: Setup workers
  hosts: workers
  tasks:
    - name: Install software
      become: yes
      apt:
        update_cache: yes
        name:
          - socat # for kubectl port-forward
          - conntrack
          - ipset
    - name: Disable swap
      command: swapoff -a
      become: true
    - name: Add modprobe support for DNS
      command: modprobe br_netfilter
      become: true
